### ISSUE TITLE
Close unitscanData window with escape key

### ISSUE THREAD

**Issue by MrBlank111** [Cruccio/unitscanData#1]
In order to close the unitscanData window it is necessary to click the cross in the top corner of the window. Sometimes we may want to react more quickly to gameplay situations while the window is open. Please allow pressing the escape key to close the unitscanData window. Thank you.

**Comment by Cruccio** [comment]
Hi, MrBlank

Thank you for your feedback! That's actually a good one: I'll add some ESC
event to also close the main window.

Cruccio

Il giorno dom 27 ago 2023 alle ore 08:27 MrBlank111 <
***@***.***> ha scritto:
