### ISSUE TITLE
Missing dangerous NPC for Blasted Lands

### ISSUE THREAD

**Issue by FlinzyHC** [Cruccio/unitscanData#3]
NPC missing from Blasted Lands.
Name: Teremus the Devourer
ID: 7846
Wowhead link for locations: 
https://www.wowhead.com/classic/npc=7846/teremus-the-devourer

**Comment by Cruccio** [comment]
Added missing mob:

NPC missing from Blasted Lands.
Name: Teremus the Devourer
ID: 7846
Wowhead link for locations:
https://www.wowhead.com/classic/npc=7846/teremus-the-devourer

Thank you!
